language: cpp

jobs:
  include:
    - arch: amd64
      os: osx
      osx_image: xcode12
      addons:
        homebrew:
          packages:
            - openssl
            - boost
            - cpprestsdk
            - protobuf
            - zeromq
      env:
        - TARGET=macos-amd64
        - OPENSSL_ROOT_DIR=$(brew --prefix openssl)
        - OPENSSL_LIB_DIR=$(brew --prefix openssl)/lib
        - OPENSSL_INCLUDE_DIR=$(brew --prefix openssl)/include
        - BOOST_ROOT=$(brew --prefix boost)
        - Boost_LIBRARY_DIR=$(brew --prefix boost)/lib
        - Boost_INCLUDE_DIR=$(brew --prefix boost)/include
        - cpprestsdk_DIR=$(brew --prefix cpprestsdk)
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file: release-$TRAVIS_TAG-$TARGET.tar.gz
        skip_cleanup: true
        on:
          repo: pashinov/dragon
          tags: true
    - arch: amd64
      os: linux
      dist: focal
      addons:
        apt:
          packages:
            - libcpprest-dev
            - libprotobuf-dev
            - protobuf-compiler
            - libzmq3-dev
      env:
        - TARGET=linux-amd64
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file: release-$TRAVIS_TAG-$TARGET.tar.gz
        skip_cleanup: true
        on:
          repo: pashinov/dragon
          tags: true
    - arch: arm64
      os: linux
      dist: focal
      addons:
        apt:
          packages:
            - libcpprest-dev
            - libprotobuf-dev
            - protobuf-compiler
            - libzmq3-dev
      env:
        - TARGET=linux-arm64
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file: release-$TRAVIS_TAG-$TARGET.tar.gz
        skip_cleanup: true
        on:
          repo: pashinov/dragon
          tags: true

script:
  - cmake -H. -Bbuild
  - cmake --build build
  - if [ -n "$TRAVIS_TAG" ]; then tar -C build -czf release-$TRAVIS_TAG-$TARGET.tar.gz dragon; fi
