sudo: required
language: shell

services:
  - docker

matrix:
  include:
    - env: BUILD_TYPE=Debug WITH_TESTS=OFF
    - env: BUILD_TYPE=Release WITH_TESTS=OFF

before_install:
  - docker build -t amsp-image .
  - docker run -v $TRAVIS_BUILD_DIR:/home/develop/amsp -it -d --name amsp amsp-image bash

script:
  - docker exec amsp cmake -H/home/develop/amsp -B/home/develop/amsp/build-$BUILD_TYPE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DWITH_TESTS=$WITH_TESTS
  - docker exec amsp cmake --build /home/develop/amsp/build-$BUILD_TYPE
