sudo: required
language: shell

services:
  - docker

matrix:
  include:
    - env: BUILD_TYPE=Debug WITH_TESTS=OFF
    - env: BUILD_TYPE=Release WITH_TESTS=OFF

before_install:
  - docker build -t falcon-image .
  - docker run -v $TRAVIS_BUILD_DIR:/home/develop/falcon -it -d --name falcon falcon-image bash

script:
  - docker exec falcon cmake -H/home/develop/falcon -B/home/develop/falcon/build-$BUILD_TYPE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DWITH_TESTS=$WITH_TESTS
  - docker exec falcon cmake --build /home/develop/falcon/build-$BUILD_TYPE
