language: cpp

jobs:
  include:
    - os: osx
      osx_image: xcode12
      addons:
        homebrew:
          packages:
            - openssl
            - boost
            - cpprestsdk
            - protobuf
            - zeromq
      env:
        - OPENSSL_ROOT_DIR=$(brew --prefix openssl)
        - OPENSSL_LIB_DIR=$(brew --prefix openssl)/lib
        - OPENSSL_INCLUDE_DIR=$(brew --prefix openssl)/include
        - BOOST_ROOT=$(brew --prefix boost)
        - Boost_LIBRARY_DIR=$(brew --prefix boost)/lib
        - Boost_INCLUDE_DIR=$(brew --prefix boost)/include
        - cpprestsdk_DIR=$(brew --prefix cpprestsdk)
    - os: linux
      dist: focal
      addons:
        apt:
          packages:
            - libcpprest-dev
            - libprotobuf-dev
            - protobuf-compiler
            - libzmq3-dev
      env:
        - CMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/cmake

script:
  - mkdir build
  - pushd build
  - cmake ..
  - make
  - popd
